# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  - solaris
  - freebsd
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    freebsd: FreeBSD
    solaris: Solaris
    386: 32bit
    amd64: 64bit
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
